table hospital
	lineageTag: 1e086f46-9803-41da-9464-6e2e27cc4c3b

	column country
		dataType: string
		lineageTag: 29e5f67b-d11c-4c77-bdba-32d475c1ae8b
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column country_code
		dataType: string
		lineageTag: ba949ce7-a938-4d68-a384-115078c1438c
		summarizeBy: none
		sourceColumn: country_code

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 60254f76-e0d5-419f-9ff8-f26dd1332cda
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column daily_occupancy_icu
		dataType: int64
		formatString: 0
		lineageTag: d28c3ced-c9ae-420b-88aa-84f6513390d2
		summarizeBy: sum
		sourceColumn: daily_occupancy_icu

		annotation SummarizationSetBy = Automatic

	column daily_occupancy_icu_per_1m
		dataType: double
		lineageTag: 9087f482-b43b-4e3c-84be-231fe59cd1c7
		summarizeBy: sum
		sourceColumn: daily_occupancy_icu_per_1m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column daily_occupancy_hosp
		dataType: int64
		formatString: 0
		lineageTag: d3b025c5-d8e4-40fe-b952-eb5eeec8aadf
		summarizeBy: sum
		sourceColumn: daily_occupancy_hosp

		annotation SummarizationSetBy = Automatic

	column daily_occupancy_hosp_per_1m
		dataType: double
		lineageTag: d6b21b9d-c4fe-49a3-aeb4-f16040083a35
		summarizeBy: sum
		sourceColumn: daily_occupancy_hosp_per_1m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weekly_admissions_icu
		dataType: int64
		formatString: 0
		lineageTag: b44bdae9-a1b4-4e1e-9ef9-2ea25f03f432
		summarizeBy: sum
		sourceColumn: weekly_admissions_icu

		annotation SummarizationSetBy = Automatic

	column weekly_admissions_icu_per_1m
		dataType: double
		lineageTag: ec04e05d-1042-4d55-b309-37ee269327b1
		summarizeBy: sum
		sourceColumn: weekly_admissions_icu_per_1m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column weekly_admissions_hosp
		dataType: int64
		formatString: 0
		lineageTag: af3d03b3-6b0e-400b-9588-525c8ea5015d
		summarizeBy: sum
		sourceColumn: weekly_admissions_hosp

		annotation SummarizationSetBy = Automatic

	column weekly_admissions_hosp_per_1m
		dataType: double
		lineageTag: a25cfc49-4c84-4499-b63f-229cf0cb47f1
		summarizeBy: sum
		sourceColumn: weekly_admissions_hosp_per_1m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition hospital = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://catalog.ourworldindata.org/garden/covid/latest/hospital/hospital.csv"),[Delimiter=",", Columns=11, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country", type text}, {"country_code", type text}, {"date", type date}, {"daily_occupancy_icu", Int64.Type}, {"daily_occupancy_icu_per_1m", type number}, {"daily_occupancy_hosp", type text}, {"daily_occupancy_hosp_per_1m", type text}, {"weekly_admissions_icu", type text}, {"weekly_admissions_icu_per_1m", type text}, {"weekly_admissions_hosp", type text}, {"weekly_admissions_hosp_per_1m", type text}}),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Changed Type",{{"daily_occupancy_hosp", Int64.Type}, {"daily_occupancy_hosp_per_1m", type number}, {"weekly_admissions_icu", Int64.Type}, {"weekly_admissions_icu_per_1m", type number}, {"weekly_admissions_hosp", Int64.Type}, {"weekly_admissions_hosp_per_1m", type number}}),
				    #"Replaced Value" = Table.ReplaceValue(#"Changed Type1","England","United Kingdom",Replacer.ReplaceText,{"country"}),
				    #"Replaced Value1" = Table.ReplaceValue(#"Replaced Value","Northern Ireland","United Kingdom",Replacer.ReplaceText,{"country"}),
				    #"Replaced Value2" = Table.ReplaceValue(#"Replaced Value1","Scotland","United Kingdom",Replacer.ReplaceText,{"country"}),
				    #"Replaced Value3" = Table.ReplaceValue(#"Replaced Value2","Wales","United Kingdom",Replacer.ReplaceText,{"country"})
				in
				    #"Replaced Value3"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

