table vaccinations_global
	lineageTag: 59591786-74f9-47ba-83d2-df59cb4551e4

	column country
		dataType: string
		lineageTag: 55924be0-4b46-46d9-a278-e49b2c896aa7
		summarizeBy: none
		sourceColumn: country

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		formatString: Long Date
		lineageTag: a399d030-f0dd-412e-8c0c-7daae7a8b5c5
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column total_vaccinations
		dataType: int64
		formatString: 0
		lineageTag: 122d68c5-203f-465a-9786-02958a6f6874
		summarizeBy: sum
		sourceColumn: total_vaccinations

		annotation SummarizationSetBy = Automatic

	column people_vaccinated
		dataType: int64
		formatString: 0
		lineageTag: 5a44576c-d279-40e8-ba67-b6507e1c5c73
		summarizeBy: sum
		sourceColumn: people_vaccinated

		annotation SummarizationSetBy = Automatic

	column people_fully_vaccinated
		dataType: int64
		formatString: 0
		lineageTag: 224a6d49-4b09-4274-a1d4-69e45f1779fa
		summarizeBy: sum
		sourceColumn: people_fully_vaccinated

		annotation SummarizationSetBy = Automatic

	column total_boosters
		dataType: string
		lineageTag: 6c25b77d-80be-4839-ba5f-7ac92c097fd4
		summarizeBy: none
		sourceColumn: total_boosters

		annotation SummarizationSetBy = Automatic

	column daily_vaccinations
		dataType: int64
		formatString: 0
		lineageTag: 8b0b39ab-0b85-4e71-887c-139fd6c298e9
		summarizeBy: sum
		sourceColumn: daily_vaccinations

		annotation SummarizationSetBy = Automatic

	column daily_vaccinations_smoothed
		dataType: double
		lineageTag: b816f308-dcb4-4b6a-b07b-0be3a12c9f57
		summarizeBy: sum
		sourceColumn: daily_vaccinations_smoothed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column daily_people_vaccinated_smoothed
		dataType: double
		lineageTag: 8e96f8d1-6512-438c-a69d-68904f56b4fd
		summarizeBy: sum
		sourceColumn: daily_people_vaccinated_smoothed

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_vaccinations_per_hundred
		dataType: double
		lineageTag: 3db5d6cb-6e94-46de-84fa-b2dba2446d3a
		summarizeBy: sum
		sourceColumn: total_vaccinations_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_vaccinated_per_hundred
		dataType: double
		lineageTag: fdaadf95-f0ef-4aec-90fd-9d2d5834bc8a
		summarizeBy: sum
		sourceColumn: people_vaccinated_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_fully_vaccinated_per_hundred
		dataType: double
		lineageTag: 1fe30437-8715-473e-b701-7d1e3a020018
		summarizeBy: sum
		sourceColumn: people_fully_vaccinated_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_boosters_per_hundred
		dataType: string
		lineageTag: 9450d693-4a3a-4294-8d22-2f2b0ee40938
		summarizeBy: none
		sourceColumn: total_boosters_per_hundred

		annotation SummarizationSetBy = Automatic

	column daily_people_vaccinated_smoothed_per_hundred
		dataType: double
		lineageTag: 31135665-df61-4b54-98f3-474950394530
		summarizeBy: sum
		sourceColumn: daily_people_vaccinated_smoothed_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column daily_vaccinations_smoothed_per_million
		dataType: double
		lineageTag: 7e2aff72-b373-4698-b7f7-0f6d50c4e4af
		summarizeBy: sum
		sourceColumn: daily_vaccinations_smoothed_per_million

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_unvaccinated
		dataType: double
		lineageTag: 7574cbdb-9592-4384-beb5-936be1abb734
		summarizeBy: sum
		sourceColumn: people_unvaccinated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column share_of_boosters
		dataType: string
		lineageTag: 304a645f-c143-47b1-b576-8dfdd44329b6
		summarizeBy: none
		sourceColumn: share_of_boosters

		annotation SummarizationSetBy = Automatic

	column total_vaccinations_interpolated
		dataType: double
		lineageTag: ef32e4d3-2533-4ab1-acbf-e4ddf90d5d01
		summarizeBy: sum
		sourceColumn: total_vaccinations_interpolated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_vaccinated_interpolated
		dataType: double
		lineageTag: 6a3a4422-246d-4ce6-a13a-40ebb08ba00d
		summarizeBy: sum
		sourceColumn: people_vaccinated_interpolated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column people_fully_vaccinated_interpolated
		dataType: double
		lineageTag: c1b532b1-2485-44c9-a557-47036ba67151
		summarizeBy: sum
		sourceColumn: people_fully_vaccinated_interpolated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_boosters_interpolated
		dataType: int64
		formatString: 0
		lineageTag: 9c448381-7a76-4972-b33a-581b488ee606
		summarizeBy: sum
		sourceColumn: total_boosters_interpolated

		annotation SummarizationSetBy = Automatic

	column total_vaccinations_no_boosters_interpolated
		dataType: double
		lineageTag: ad813658-cd3d-4c0c-a683-d4e7add02eef
		summarizeBy: sum
		sourceColumn: total_vaccinations_no_boosters_interpolated

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column total_vaccinations_no_boosters_per_hundred_interpolated
		dataType: string
		lineageTag: b5920488-b0d8-4c19-a58a-05ea70f757f2
		summarizeBy: none
		sourceColumn: total_vaccinations_no_boosters_per_hundred_interpolated

		annotation SummarizationSetBy = Automatic

	column rolling_vaccinations_6m
		dataType: double
		lineageTag: 75cd4868-5493-4711-b061-570a2886199c
		summarizeBy: sum
		sourceColumn: rolling_vaccinations_6m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_vaccinations_6m_per_hundred
		dataType: double
		lineageTag: 7c0d4440-4042-4b72-b585-064ff34be291
		summarizeBy: sum
		sourceColumn: rolling_vaccinations_6m_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_vaccinations_9m
		dataType: double
		lineageTag: 84bd6f2e-20eb-475a-95e2-a6170180d5e6
		summarizeBy: sum
		sourceColumn: rolling_vaccinations_9m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_vaccinations_9m_per_hundred
		dataType: double
		lineageTag: e1daee64-3e84-47c3-a703-6f38c843bf3c
		summarizeBy: sum
		sourceColumn: rolling_vaccinations_9m_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_vaccinations_12m
		dataType: double
		lineageTag: 449a03d2-e602-4ea8-a5fd-75e68d90f10b
		summarizeBy: sum
		sourceColumn: rolling_vaccinations_12m

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column rolling_vaccinations_12m_per_hundred
		dataType: double
		lineageTag: 37dea8cc-f105-4742-b450-3e302e9b6d7b
		summarizeBy: sum
		sourceColumn: rolling_vaccinations_12m_per_hundred

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition vaccinations_global = m
		mode: import
		source =
				let
				    Source = Csv.Document(Web.Contents("https://catalog.ourworldindata.org/garden/covid/latest/vaccinations_global/vaccinations_global.csv"),[Delimiter=",", Columns=29, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"country", type text}, {"date", type date}, {"total_vaccinations", Int64.Type}, {"people_vaccinated", Int64.Type}, {"people_fully_vaccinated", Int64.Type}, {"total_boosters", type text}, {"daily_vaccinations", Int64.Type}, {"daily_vaccinations_smoothed", type number}, {"daily_people_vaccinated_smoothed", type number}, {"total_vaccinations_per_hundred", type number}, {"people_vaccinated_per_hundred", type number}, {"people_fully_vaccinated_per_hundred", type number}, {"total_boosters_per_hundred", type text}, {"daily_people_vaccinated_smoothed_per_hundred", type number}, {"daily_vaccinations_smoothed_per_million", type number}, {"people_unvaccinated", type number}, {"share_of_boosters", type text}, {"total_vaccinations_interpolated", type number}, {"people_vaccinated_interpolated", type number}, {"people_fully_vaccinated_interpolated", type number}, {"total_boosters_interpolated", Int64.Type}, {"total_vaccinations_no_boosters_interpolated", type number}, {"total_vaccinations_no_boosters_per_hundred_interpolated", type text}, {"rolling_vaccinations_6m", type number}, {"rolling_vaccinations_6m_per_hundred", type number}, {"rolling_vaccinations_9m", type number}, {"rolling_vaccinations_9m_per_hundred", type number}, {"rolling_vaccinations_12m", type number}, {"rolling_vaccinations_12m_per_hundred", type number}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

